# Gradle Properties
org.gradle.jvmargs=-Xmx4G
org.gradle.workers.max=5
org.gradle.parallel=true
org.gradle.configuration-cache=false
org.gradle.java.installations.auto-download=true

# Mod Properties
mod.id=cwb
mod.version=4.1.0
mod.name=Cubes Without Borders
mod.description=Allows you to play Minecraft in a borderless fullscreen window.
mod.environment=client
mod.author=Kira-NT
mod.license=MIT
mod.sources=https://github.com/Kira-NT/cubes-without-borders
mod.modrinth.id=ETlrkaYF
mod.curseforge.id=975120

# Dependencies
dependencies.loom=1.17-SNAPSHOT
dependencies.minecraft=26.3
dependencies.java=25
dependencies.fabric-loader=0.19.5
dependencies.forge=26.3-66.0.5
dependencies.neoforge=26.3.0.23-beta
dependencies.fancymodloader=11.0.0
dependencies.sodium=mc26.3-0.9.2-fabric
dependencies.modmenu=21.0.0
dependencies.cloth-config=26.3.159+fabric
dependencies.yacl=3.9.7+26.3-fabric
